version: "3"

services:
  ghci:
    image: haskell:8.6.3
    command: ghci
    volumes:
      - ./exercises:/exercises
    working_dir: /exercises
  submit:
    build:
      context: .
      dockerfile: submit.dockerfile
    env_file:
      - mat-numbers.env
    volumes:
      - ./:/repo
    working_dir: /repo
